'''
@author: Rohit Sharma
Date: 01-Aug-2022

Description: This script decrypt all aws certificates stored in a folder. 
For decryption you need filekey.key generated by encrypt-test.py script.
'''
from cryptography.fernet import Fernet
import os
import glob

path = '/home/awadh/certs'
all_files = glob.glob(path + "/*")
for filename in all_files:
	with open('/home/awadh/filekey.key', 'rb') as filekey:
		key = filekey.read()

	fernet = Fernet(key)
	# opening the encrypted file
	with open(filename, 'rb') as enc_file:
		encrypted = enc_file.read()

	# decrypting the file
	decrypted = fernet.decrypt(encrypted)

	# opening the file in write mode and
	# writing the decrypted data
	with open(filename, 'wb') as dec_file:
		dec_file.write(decrypted)
